# worldIdiot
# Version: ${project.version}
# Gitgub: https://github.com/mc-serverworld/worldidiot
data:
  mysql:
    host: localhost
    port: 3306
    username: root
    password: open
    database: worldprofile