# ${project.name}
# Version: ${project.version}
# Gitgub: https://github.com/mc-serverworld/worldidiot
data:
  mysql:
    host: 127.0.0.1
    port: 3306
    username: root
    password: open
    database: worldIdiot